name: Docker Login Action

on:
  push:
    branches:
      - main

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Login a Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
